let names = ["Iúti Stark",
  "Hardwin Schwangau",
  "Tunric Sherbourne",
  "Reginwal Keenbeater",
  "Hademar Underhill",
  "Haret Purles",
  "Aldwin Jewelage",
  "Turold Hitchcock",
  "Arthorr Woolsplit",
  "Adysair Ogrebearer",
  "Morin Boldbeam",
  "Jagelin Shern",
  "Taniel Plateweave",
  "Emanuel Mapson",
  "Wallace Follet",
  "Wolfgang Bitterclaw",
  "Odward Stoke",
  "Arikail Rocktwist",
  "Kjartan Vann",
  "Svidbalki Glebard"
]

let weapons = [
  { name: "Dagger",
    edged: true,
    bludgeoning: false,
    polearm: false,
    piercing: true,
    hands: 1,
    cost: "low",
  },
  { name: "Sword",
    edged: true,
    bludgeoning: false,
    polearm: false,
    piercing: true,
    hands: 1,
    cost: "medium",
  },
  { name: "Greatsword",
    edged: true,
    bludgeoning: false,
    polearm: false,
    piercing: false,
    hands: 2,
    cost: "high",
  },
  { name: "Club",
    edged: false,
    bludgeoning: true,
    polearm: false,
    piercing: false,
    hands: 1,
    cost: "low",
  },
  { name: "Mace",
    edged: false,
    bludgeoning: true,
    polearm: false,
    piercing: false,
    hands: 1,
    cost: "medium",
  },
  { name: "Morning Star",
  edged: false,
  bludgeoning: true,
  polearm: false,
  piercing: true,
  hands: 1,
  cost: "medium",
},
  { name: "Greatclub",
    edged: false,
    bludgeoning: true,
    polearm: false,
    piercing: false,
    hands: 2,
    cost: "low",
  },
  { name: "Spear",
    edged: false,
    bludgeoning: false,
    polearm: true,
    piercing: true,
    hands: 2,
    cost: "medium",
  },
  { name: "Halberd",
    edged: true,
    bludgeoning: false,
    polearm: true,
    piercing: true,
    hands: 2,
    cost: "high",
  },
  { name: "Quarterstaff",
    edged: false,
    bludgeoning: true,
    polearm: true,
    piercing: false,
    hands: 2,
    cost: "low",
  },
  { name: "Axe",
    edged: true,
    bludgeoning: false,
    polearm: false,
    piercing: false,
    hands: 1,
    cost: "medium",
  },
  { name: "Battle Axe",
    edged: true,
    bludgeoning: false,
    polearm: false,
    piercing: false,
    hands: 2,
    cost: "high",
  }
]